### ISSUE TITLE
[playoff remap] 2017wagg incorrectly configured as 8 alliance events

### ISSUE THREAD

**Issue by timtim17** [the-blue-alliance/the-blue-alliance-data#42]
2017 ~~& 2018's~~ Washington Girls' Gen event pages have the events listed as 8 alliance playoffs/show quarterfinal matches that did not happen.
![2018wagg playoffs](https://i.imgur.com/pTDnRKt.png)

2017wagg
~~2018wagg (frc.events has 2018wamap)~~ _edit 11/17: 2018wagg is now displayed correctly_

Also, as a sidenote 2018wagg also has its event name as "Washington Girls' Generation 2018 2018."

**Comment by gregmarra** [comment]
I fixed the 2018wagg event name repeating 2018.

I don't know how to fix the playoff results. We need to write up documentation for that, since others know how to do it and I don't.

**Comment by timtim17** [comment]
Regarding the event name: not sure if this is just a weird caching issue or something but the event name still appears to repeat 2018

![image](https://user-images.githubusercontent.com/6354860/49126213-99ca4480-f277-11e8-9ad2-84c3640a271f.png)

**Comment by gregmarra** [comment]
Thanks for reporting. I've fixed it now.

**Comment by timtim17** [comment]
2018wagg now appears to display correctly, so I'm going to close this unless you all need it to track something.

![image](https://user-images.githubusercontent.com/6354860/49829935-a903c480-fd44-11e8-9935-aa65c27f2778.png)

**Comment by gregmarra** [comment]
Austin is 2017 also fixed?

**Comment by timtim17** [comment]
Nope, never mind: it appears 2017wagg is not fixed. My mistake.
